# Generated by Django 2.1.4 on 2019-12-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191230_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='offline_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='下架日期'),
        ),
    ]
